services:
  database-api:
    image: database-api:latest
    container_name: database-api
    restart: always
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - MAX_CONCURRENT_REQUESTS=200
      - POSTGRESQL_MAX_CONCURRENT=100
      - MONGODB_MAX_CONCURRENT=100
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
    name: api-proxy_proxy_net  # 指定正确的外部网络名称 