services:
  database-api-private:
    image: database-api-private:latest
    container_name: database-api-private
    restart: always
    ports:
      - "3011:3011"
    volumes:
      - ./config:/app/config
    environment:
      - PORT=3011
      - MAX_CONCURRENT_REQUESTS=200
      - POSTGRESQL_MAX_CONCURRENT=100
      - MONGODB_MAX_CONCURRENT=100
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
    name: api-proxy_proxy_net 